name: "🧩 API change request"
description: "Propose a change to existing API behavior"
title: "[API]: <short summary>"
labels: ["api-change"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose changes to current endpoints or response formats.
  - type: dropdown
    id: endpoint
    attributes:
      label: Endpoint
      options:
        - /analyze
        - /quick-score
        - /metadata
        - Other
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: Describe the current request/response or logic.
      render: JSON
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: Proposed behavior
      description: Describe the proposed change. Include migration guidance if breaking.
      render: JSON
    validations:
      required: true
  - type: dropdown
    id: breaking
    attributes:
      label: Breaking change?
      options:
        - "No"
        - "Possibly"
        - "Yes"
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact & migration (if breaking)
  - type: textarea
    id: extra
    attributes:
      label: Additional context
