name: "📝 Documentation update"
description: "Propose changes to README, Wiki, or RapidAPI docs"
title: "[Docs]: <short summary>"
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us keep the docs excellent. Tell us what needs to change.
  - type: dropdown
    id: area
    attributes:
      label: Documentation area
      options:
        - README
        - Wiki (Home)
        - Wiki (Getting Started)
        - Wiki (Endpoints)
        - Wiki (Examples)
        - Wiki (FAQ)
        - Wiki (Changelog)
        - RapidAPI docs
        - Other
    validations:
      required: true
  - type: input
    id: page_url
    attributes:
      label: Page URL (if applicable)
      placeholder: "Link to the page to update"
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
      description: Provide the text or examples you propose to add/update.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / examples
