name: "✨ Feature request"
description: "Suggest an idea or improvement for Ultimate SEO Analyzer API"
title: "[Feature]: <short summary>"
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Help us understand the problem and the proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you facing? What is the user story?
      placeholder: "As a developer, I want ... so that ..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your solution. Include endpoint shape, parameters, and response fields if applicable.
      placeholder: |
        New endpoint: /quick-score
        Params: url, includeSuggestions=true
        Response: { score: 92, ... }
      render: JSON
    validations:
      required: true
  - type: checkboxes
    id: change_type
    attributes:
      label: Type of change
      options:
        - label: New endpoint
        - label: New parameters
        - label: New response fields
        - label: Improved scoring/logic
        - label: Other
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Describe any alternative solutions or features you've considered.
  - type: dropdown
    id: breaking
    attributes:
      label: Breaking change?
      options:
        - "No"
        - "Possibly"
        - "Yes"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - nice to have
        - important
        - urgent
  - type: textarea
    id: extra
    attributes:
      label: Additional context / mockups
      description: Add any other context, diagrams, or screenshots.
